### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Harshkumar62367** [Tech-Phantoms/community#141]
### Name

Harsh Kumar

### Discord Username (if applicable)

Harsh_Y20#5851

### Additional Context

I want to join Tech Phantoms community to increase my knowledge in the world of api's and contribute more to open source

**Comment by Harshkumar62367** [comment]
@Souvikns , I still haven't received any invitation after two days, thought there is some problem in the bot, can you pls look into this

**Comment by Souvikns** [comment]
Hey @Harshkumar62367 sorry for the inconvenience, there was some issue with the bot as we were updating the labels I just sent you a invitation manually so check your email you should get the invitation now.

**Comment by Harshkumar62367** [comment]
Thanks @Souvikns, I got the invitation now
