### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hariketsheth** [Tech-Phantoms/community#142]
### Name

Hariket Sheth

### Discord Username (if applicable)

Hariket Sheth#1969

### Additional Context

Looking for some productive Opensource opportunities and a chance to contribute

**Comment by hariketsheth** [comment]
@Souvikns I haven't received the invitation

**Comment by Souvikns** [comment]
I just send you an invitation, I think the bot is acting up again, thanks for letting me know I will look into it.
